### ISSUE TITLE
为什么我只能拿到一个用户？

### ISSUE THREAD

**Issue by xddun** [VariantConst/OpenWebUI-Monitor#14]
我是有一个管理员和一个普通用户的，但是这个页面只能看到一个用户，如何刷新呢？

![image](https://github.com/user-attachments/assets/afd04d16-ceed-4765-91a9-cdb650d5c930)

**Comment by xddun** [comment]
```
services:
  app:
    image: docker.io/variantconst/openwebui-monitor:latest
    ports:
      - "8081:3000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-openwebui}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-openwebui_monitor}
      - OPENWEBUI_DOMAIN=${OPENWEBUI_DOMAIN}
      - OPENWEBUI_API_KEY=${OPENWEBUI_API_KEY}
      - API_KEY=${API_KEY}
      - INIT_BALANCE=${INIT_BALANCE:-1}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    profiles:
      - ${POSTGRES_HOST:+never}
      - ${POSTGRES_HOST:-default}
    image: postgres:15-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-openwebui}
      - POSTGRES_DB=${POSTGRES_DATABASE:-openwebui_monitor}
    volumes:
      - /root/OpenWebUI-Monitor/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

```


我改写了docker compose.yaml 之后重启了Monitor， 打开用户管理页面后什么也没有了，，很怪异。。
